"""Step 7 — assemble the 30 blocks and run the real model.

Run:  uv run python steps/07_forward.py

Everything here is our own code. transformers appears only as the source of the
saved reference tensors, which we diff against layer by layer.
"""

import sys
import time
from pathlib import Path

import torch

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from toyllm.model import SmolLM2
from toyllm.tokenizer import BPETokenizer

ROOT = Path(__file__).resolve().parent.parent          # code/poc
MODEL_DIR = ROOT.parent / "models" / "SmolLM2-135M"    # code/models
REF_PATH = ROOT.parent / "reference" / "smollm2_135m_forward.pt"


def rule(title):
    print(f"\n{'=' * 70}\n{title}\n{'=' * 70}")


def main():
    rule("1. what a block is")
    print("""    h = x + attn(input_layernorm(x))
    y = h + mlp(post_attention_layernorm(h))""")
    print("\n  Pre-norm: each sublayer reads a *normalized copy* of the residual")
    print("  stream, and writes back into the un-normalized stream. So a value")
    print("  written at block 0 reaches block 29 without ever being rescaled.")
    print("\n  Two easy silent bugs here:")
    print("    - normalizing x instead of h before the MLP")
    print("    - post-norm ordering, y = norm(h + mlp(h)) — the 2017 arrangement")
    print("  Both run and both produce text.")

    rule("2. loading")
    t0 = time.perf_counter()
    model = SmolLM2.from_pretrained(MODEL_DIR)
    load_s = time.perf_counter() - t0
    cfg = model.cfg
    print(f"  loaded in {load_s:.1f}s")
    print(f"  {model.num_parameters():,} parameters  (step 1 predicted 134,515,008)")
    print(f"  {cfg.num_hidden_layers} blocks, lm_head tied to embed_tokens: "
          f"{model.lm_head.weight is model.embed_tokens.weight}")

    tok = BPETokenizer.from_file(MODEL_DIR)
    prompt = "The capital of France is"
    ids = torch.tensor([tok.encode(prompt)])

    rule("3. the residual stream grows, then the final norm tames it")
    with torch.no_grad():
        logits, hs = model(ids, output_hidden_states=True)
    print(f"  {'index':>6}   {'what':<24}{'max |h|':>12}")
    for i in [0, 1, 2, 6, 12, 18, 24, 29, 30]:
        what = ("embedding output" if i == 0 else
                "after final norm" if i == cfg.num_hidden_layers else
                f"input to block {i}")
        print(f"  {i:>6}   {what:<24}{hs[i].abs().max():>12.2f}")
    print("\n  Activations climb by four orders of magnitude across the stack —")
    print("  nothing normalizes the stream itself, only the copies each sublayer")
    print("  reads. The single final RMSNorm brings it back to O(10) for lm_head.")

    rule("4. layer-by-layer validation against transformers")
    if not REF_PATH.exists():
        print("  reference/ missing — run steps/00_reference.py first")
        return
    ref = torch.load(REF_PATH, weights_only=True)
    assert torch.equal(ids, ref["input_ids"]), "our tokenizer disagrees with HF's"
    print(f"  our tokenizer reproduces HF's input_ids: {ids.tolist()[0]}")

    R = ref["hidden_states"]
    print(f"\n  {'layer':>6}{'max |diff|':>14}{'relative':>13}")
    worst = 0.0
    for i, (a, b) in enumerate(zip(hs, R)):
        rel = ((a - b).abs().max() / b.abs().max()).item()
        worst = max(worst, rel)
        if i < 3 or i % 6 == 0 or i >= cfg.num_hidden_layers - 1:
            print(f"  {i:>6}{(a - b).abs().max():>14.3e}{rel:>13.3e}")
    print(f"\n  worst relative error over all {len(hs)} layers: {worst:.3e}")
    print("  Growing smoothly, no jump — a wrong operator shows as a step change")
    print("  at one layer, which is exactly why this is checked per layer.")

    rule("5. logits")
    rel = ((logits - ref["logits"]).abs().max() / ref["logits"].abs().max()).item()
    print(f"  relative error vs transformers: {rel:.3e}")
    print(f"  argmax identical at every position: "
          f"{torch.equal(logits.argmax(-1), ref['logits'].argmax(-1))}")
    print(f"\n  next-token distribution after {prompt!r}:")
    top = logits[0, -1].topk(5)
    for score, tid in zip(top.values, top.indices):
        print(f"    {tok.decode([tid.item()]):<12} logit {score:+.3f}")

    rule("6. the first sentence generated by our own code")
    t0 = time.perf_counter()
    with torch.no_grad():
        out = model.generate(ids, max_new_tokens=20)
    ours_s = time.perf_counter() - t0
    n_new = out.shape[1] - ids.shape[1]
    print(f"  {tok.decode(out[0].tolist())!r}")
    print(f"\n  identical to the transformers baseline: {torch.equal(out, ref['greedy_20'])}")
    print(f"  {n_new} tokens in {ours_s:.2f}s  ({n_new / ours_s:.1f} tok/s)")
    print(f"  transformers, same machine (step 0): ~12.9 tok/s")

    prompt_len, redundant = ids.shape[1], sum(range(ids.shape[1], ids.shape[1] + n_new))
    print(f"\n  Do not read that as 'we are faster'. We have no KV cache at all:")
    print(f"  generating token n re-runs all n-1 previous tokens through 30 blocks.")
    print(f"  For this {prompt_len}-token prompt and {n_new} new tokens we pushed "
          f"{redundant:,} token-forwards")
    print(f"  through the stack where {n_new} would have sufficed. It only looks")
    print(f"  competitive because the sequence is tiny and we skip the framework")
    print(f"  overhead in generate(). At 500 tokens the quadratic term dominates —")
    print(f"  step 8 adds the cache and the gap inverts.")


if __name__ == "__main__":
    main()
